### PR TITLE
Add terrain deformation

### PR DESCRIPTION
**Pull request by diwako**

### CODE REVIEW

**Review by b-mayr-1984 — CHANGES_REQUESTED** [review]
@diwako I think the file `.editorconfig` should be removed.

**Comment by diwako** [comment]
Don't see why, arma ignores it, is used for correct formatting when using vscode and making scripts.

**Comment by b-mayr-1984** [comment]
@diwako there is really nothing wrong with you using such a mechanism for vscode and having the file on your local disk. 🙂 
But the file has nothing to do with the subject matter of this repository.

If you imagine X different developers with Y different editors adding Z different files that are just config files for their personal IDE, the repository ends up with a lot of clutter most devs won't have use for and might just get distracted by.

**Comment by diwako** [comment]
The `.editorconfig` is an [editor agnostic standard](https://editorconfig.org/). If this would be a PR which adds a `.vscode` or `.ide` folder then I would complain as well. This file is there so people have the correct indentations, correct line endings and correct char set, so that pull requests do not have massive un-needed changes as some IDE's have different default format settings.

**Comment by b-mayr-1984** [comment]
Ok, I buy it now 😅

**Pull request merged**
