### PR TITLE
ShellTracker Update

### LINKED ISSUE #38: shelltracker increasingly broken with time passing
With increasing time spent in the mission the [shell tracking feature](https://docs.google.com/presentation/d/1BGDOxqqZw4T6js3oQ4mPr4E7f8NLZsPS85MUAAIYvco/edit#slide=id.g27941e9ac27_1_9) shows to be increasingly broken. 
Shells being fired are then not shown in the `systemChat` anymore and also the map markers are not visible.

### Video proof
- [Struwe/Alecandru no Arti tracking](https://www.youtube.com/watch?v=PfVHyE1Ipxg&t=3440s)
- [Struwe showing debug hit message (but no shooting messages)](https://www.youtube.com/watch?v=PfVHyE1Ipxg&t=4756s)
- [Bror showing debug hit message (but no shooting messages)](https://youtu.be/PfVHyE1Ipxg?si=wQd9mSkSdfGApC1F&t=5026)
- [Bror showing debug hit message (but no shooting messages)](https://youtu.be/PfVHyE1Ipxg?si=iDpvlPykht01kGS2&t=5530)
- [Bestefar showing debug hit message (but no shooting messages)](https://youtu.be/PfVHyE1Ipxg?si=Sozw0JM9-Oroypg6&t=5630)

### Most likely cause
[GetInMan](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#GetInMan) is described as being _Persistent on respawn if assigned where unit was [local](https://community.bistudio.com/wiki/Multiplayer_Scripting#Locality)_. 
The later is probably not the case, because [fn_postInit.sqf#L6](https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/blob/main/scripts/shelltracker/functions/fn_postInit.sqf#L6) makes sure it is assigned where a Zeus is local, not the artillery players.

### Further reading
- https://forums.bohemia.net/forums/topic/190752-event-handler-persist-after-respawn/

### PR DESCRIPTION
**Pull request by senshi-x**
- Added re-init of GetInMan EH on respawn. Fixes #38
- Added unit-specific re-init handling instead of allPlayers. Improves performance load on respawn/JIP.

### CODE REVIEW

**Comment by senshi-x** [comment]
Tested locally with multiple clients.

**Comment by b-mayr-1984** [comment]
@senshi-x when testing locally in multiplayer I get this error message
```
11:26:51 Error in expression <





if !(hasInterface) exitWith {};

params [["_unitsToUpdate", allPlayers, [>
11:26:51   Error position: <params [["_unitsToUpdate", allPlayers, [>
11:26:51   Error Params: Type String, expected Array
11:26:51 File C:\Users\Bernhard-WS\Documents\Arma 3 - Other Profiles\Bernhard\mpmissions\Shoot_and_Scoot.Tanoa\scripts\shelltracker\functions\fn_initTracker.sqf, line 11
```

Does not happen on dedicated server though.

**Comment by senshi-x** [comment]
I never test local, only dedicated.
Still, you'll see that on DS as well. It's caused by Arma throwing an Error instead of a warning in case of type checking on `params` when a defaultvalue is used.

**Comment by b-mayr-1984** [comment]
> I never test local, only dedicated. Still, you'll see that on DS as well. It's caused by Arma throwing an Error instead of a warning in case of type checking on `params` when a defaultvalue is used.

Hm if the type check of `params` is to blame, could we remove the type check and do it afterwards with checks and `exitWith` instead? 

But which call is feeding a wrong type in the first place? 🤔

**Comment by senshi-x** [comment]
Sure you can do workarounds, but why? It works just as it should.

There's only a single place where this script is called without units, so it's easy to pinpoint: It's the postInit call.
https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/pull/40/files#diff-0fbb73040b480729a4030dfe426ebebf59a1278b5a1775909243429892b17ff3R12

**Comment by b-mayr-1984** [comment]
> Sure you can do workarounds, but why? It works just as it should.

In my experience a code base deteriorates if warnings are just ignored and every developer gets used to warnings poping up. 
When this habbit sinks in, bugs are then slipping through, because no one takes care of warning messages anymore.

**Comment by nomisum** [comment]
where is string coming from? 

`[[_unit]] remoteExecCall ["shellTracker_fnc_initTracker"];`

there shouldnt be a string involved, shouldnt there?

**Comment by senshi-x** [comment]
> where is string coming from?
> 
> `[[_unit]] remoteExecCall ["shellTracker_fnc_initTracker"];`
> 
> there shouldnt be a string involved, shouldnt there?

That's not the line I linked to. :) It comes from the very last line in postInit (line 12). If you `call` a fnc without arguments, Arma automatically uses the source function name and a boolean ( I forgot what that one stands for) as args.
In this case,  `_this` inside initTracker is:
`["postInit",true]`

And there's your string.

EDIT: If you really are so bothered by this SQF bug, just make it `[allPlayers] call ...` in that line.

**Comment by senshi-x** [comment]
> > Sure you can do workarounds, but why? It works just as it should.
> 
> In my experience a code base deteriorates if warnings are just ignored and every developer gets used to warnings poping up. When this habbit sinks in, bugs are then slipping through, because no one takes care of warning messages anymore.

Sure, your principle is right. In principle. But working around false positives caused by engine bugs by weakening your own code strengths such as full typechecks, performance and legibility is definitely more harmful overall and will lead to more errors in the future.

**Comment by b-mayr-1984** [comment]
> EDIT: If you really are so bothered by this SQF bug, just make it `[allPlayers] call ...` in that line.

I will go with this solution. Thx 🙂

**Comment by y0014984** [comment]
> If you `call` a fnc without arguments, Arma automatically uses the source function name and a boolean ( I forgot what that one stands for) as args.

Are you sure? The wiki says:

> arguments: [Anything](https://community.bistudio.com/wiki/Anything) - (Optional, default [nil](https://community.bistudio.com/wiki/nil)) arguments that are passed to the method in the [_this](https://community.bistudio.com/wiki/Magic_Variables#this) variable

So the arguments default to nil I would say, see https://community.bistudio.com/wiki/call

**Comment by senshi-x** [comment]
> > If you `call` a fnc without arguments, Arma automatically uses the source function name and a boolean ( I forgot what that one stands for) as args.
> 
> Are you sure. The wiki says:
> 
> > arguments: [Anything](https://community.bistudio.com/wiki/Anything) - (Optional, default [nil](https://community.bistudio.com/wiki/nil)) arguments that are passed to the method in the [_this](https://community.bistudio.com/wiki/Magic_Variables#this) variable
> 
> So the arguments default to nil I would say, see https://community.bistudio.com/wiki/call

I'm sure because I tested it. 🤷 Simply add a diag_log(_this) inside the initTracker.sqf to replicate/verify. I do not know why this happens, and did not further investigate it either.

EDIT: You can also checkout the previous commit, which included exactly that debug/diag_log stuff because I was confused as well what was going on. ;)

**Comment by b-mayr-1984** [comment]
@senshi-x we just verified the bugfix on the dedicated server (with @nomisum and @PulsarNeutronStar). 
It works now also after respawn. Thx 🙂

**Pull request merged**
